spring:
  datasource:
    url: jdbc:mysql://localhost/expensetracker?user=root
    username: root
    password: root
# add your own username and password and db name
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
